const PDFDocument = require('pdfkit');
const Expense = require('../models/Expense');
const Income = require('../models/Income');

// @desc    Export PDF report
// @route   GET /api/export/pdf
const exportPDF = async (req, res) => {
  try {
    const expenses = await Expense.find({ user: req.user._id }).sort({ date: -1 });
    const incomes = await Income.find({ user: req.user._id }).sort({ date: -1 });

    const totalIncome = incomes.reduce((sum, i) => sum + i.amount, 0);
    const totalExpenses = expenses.reduce((sum, e) => sum + e.amount, 0);
    const balance = totalIncome - totalExpenses;

    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=FinTrack-Report-${Date.now()}.pdf`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, 595, 80).fill('#7c3aed');
    doc.fillColor('white').fontSize(28).font('Helvetica-Bold').text('FinTrack', 40, 20);
    doc.fontSize(12).font('Helvetica').text('Financial Report', 40, 52);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 350, 52, { align: 'right' });

    doc.fillColor('#1e293b').moveDown(3);

    // User info
    doc.fontSize(14).font('Helvetica-Bold').text(`Report for: ${req.user.name}`, 40, 100);
    doc.fontSize(11).font('Helvetica').fillColor('#64748b').text(req.user.email, 40, 118);

    // Summary cards
    doc.moveDown(2);
    const summaryY = 145;

    // Income box
    doc.rect(40, summaryY, 155, 65).fill('#f0fdf4').stroke('#bbf7d0');
    doc.fillColor('#166534').fontSize(11).font('Helvetica-Bold').text('Total Income', 55, summaryY + 10);
    doc.fontSize(20).text(`Rs.${totalIncome.toFixed(2)}`, 55, summaryY + 28);

    // Expense box
    doc.rect(210, summaryY, 155, 65).fill('#fef2f2').stroke('#fecaca');
    doc.fillColor('#991b1b').fontSize(11).font('Helvetica-Bold').text('Total Expenses', 225, summaryY + 10);
    doc.fontSize(20).text(`Rs.${totalExpenses.toFixed(2)}`, 225, summaryY + 28);

    // Balance box
    doc.rect(380, summaryY, 155, 65).fill(balance >= 0 ? '#eff6ff' : '#fef2f2').stroke(balance >= 0 ? '#bfdbfe' : '#fecaca');
    doc.fillColor(balance >= 0 ? '#1e40af' : '#991b1b').fontSize(11).font('Helvetica-Bold').text('Net Balance', 395, summaryY + 10);
    doc.fontSize(20).text(`Rs.${balance.toFixed(2)}`, 395, summaryY + 28);

    // Expense table
    doc.moveDown(5);
    doc.fillColor('#1e293b').fontSize(16).font('Helvetica-Bold').text('Expense History', 40, 240);

    const expTableTop = 265;
    const cols = { date: 40, desc: 120, cat: 280, amount: 450 };

    // Table header
    doc.rect(40, expTableTop, 515, 22).fill('#7c3aed');
    doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
    doc.text('Date', cols.date + 5, expTableTop + 6);
    doc.text('Description', cols.desc + 5, expTableTop + 6);
    doc.text('Category', cols.cat + 5, expTableTop + 6);
    doc.text('Amount', cols.amount + 5, expTableTop + 6);

    let y = expTableTop + 22;
    expenses.slice(0, 20).forEach((exp, i) => {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.rect(40, y, 515, 20).fill(i % 2 === 0 ? '#f8fafc' : 'white');
      doc.fillColor('#334155').fontSize(9).font('Helvetica');
      doc.text(new Date(exp.date).toLocaleDateString(), cols.date + 5, y + 5);
      doc.text(exp.description.substring(0, 25), cols.desc + 5, y + 5);
      doc.text(exp.category, cols.cat + 5, y + 5);
      doc.fillColor('#dc2626').text(`-Rs.${exp.amount.toFixed(2)}`, cols.amount + 5, y + 5);
      y += 20;
    });

    // Income table
    y += 20;
    if (y > 650) { doc.addPage(); y = 40; }

    doc.fillColor('#1e293b').fontSize(16).font('Helvetica-Bold').text('Income History', 40, y);
    y += 25;

    doc.rect(40, y, 515, 22).fill('#059669');
    doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
    doc.text('Date', cols.date + 5, y + 6);
    doc.text('Source', cols.desc + 5, y + 6);
    doc.text('Description', cols.cat + 5, y + 6);
    doc.text('Amount', cols.amount + 5, y + 6);
    y += 22;

    incomes.slice(0, 20).forEach((inc, i) => {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.rect(40, y, 515, 20).fill(i % 2 === 0 ? '#f0fdf4' : 'white');
      doc.fillColor('#334155').fontSize(9).font('Helvetica');
      doc.text(new Date(inc.date).toLocaleDateString(), cols.date + 5, y + 5);
      doc.text(inc.source.substring(0, 25), cols.desc + 5, y + 5);
      doc.text((inc.description || '').substring(0, 25), cols.cat + 5, y + 5);
      doc.fillColor('#059669').text(`+Rs.${inc.amount.toFixed(2)}`, cols.amount + 5, y + 5);
      y += 20;
    });

    // Footer
    doc.fontSize(9).fillColor('#94a3b8').text('Generated by FinTrack — Modern Expense Tracker', 40, 800, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: err.message });
  }
};

module.exports = { exportPDF };